version: '3'
services:
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 990813
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
#      - 挂载
#    volumes:
#      - /root/docker-compose/mysql/data:/var/lib/mysql
#      - /root/docker-compose/mysql/config/my.cnf:/etc/mysql/my.cnf
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password

#启动命令
#docker-compose up -d


